/* ===========================================================
   CHARACTER DATABASE
   Single unified list - lvl 1-4 = beginner/elementary,
   lvl 5-8 = intermediate, lvl 9-10 = advanced.
   Tags: battle | feast | build  (thematic vocabulary)
=========================================================== */
const CHARACTER_DB = [
  // == LEVELS 1-4 · Elementary ==
  // People & basic
  {hz:'人',py:'rén',en:'person',lvl:1},{hz:'大',py:'dà',en:'big',lvl:1},
  {hz:'小',py:'xiǎo',en:'small',lvl:1},{hz:'我',py:'wǒ',en:'I/me',lvl:1},
  {hz:'你',py:'nǐ',en:'you',lvl:1},{hz:'他',py:'tā',en:'he/him',lvl:1},
  {hz:'她',py:'tā',en:'she/her',lvl:1},{hz:'们',py:'men',en:'plural suffix',lvl:1},
  {hz:'这',py:'zhè',en:'this',lvl:1},{hz:'那',py:'nà',en:'that',lvl:1},
  {hz:'什么',py:'shénme',en:'what',lvl:1},{hz:'哪',py:'nǎ',en:'which',lvl:1},
  {hz:'谁',py:'shéi',en:'who',lvl:1},{hz:'哪里',py:'nǎlǐ',en:'where',lvl:1},
  {hz:'为什么',py:'wèishéme',en:'why',lvl:1},{hz:'怎么',py:'zěnme',en:'how',lvl:1},
  // Nature
  {hz:'山',py:'shān',en:'mountain',lvl:1},{hz:'水',py:'shuǐ',en:'water',lvl:1},
  {hz:'火',py:'huǒ',en:'fire',lvl:1},{hz:'木',py:'mù',en:'wood/tree',lvl:1},
  {hz:'日',py:'rì',en:'sun/day',lvl:2},{hz:'月',py:'yuè',en:'moon/month',lvl:2},
  {hz:'天',py:'tiān',en:'sky/day',lvl:2},{hz:'地',py:'dì',en:'earth',lvl:2},
  {hz:'风',py:'fēng',en:'wind',lvl:2},{hz:'雨',py:'yǔ',en:'rain',lvl:2},
  {hz:'雪',py:'xuě',en:'snow',lvl:2},{hz:'云',py:'yún',en:'cloud',lvl:2},
  {hz:'石',py:'shí',en:'stone/rock',lvl:2},{hz:'土',py:'tǔ',en:'soil/earth',lvl:2},
  {hz:'草',py:'cǎo',en:'grass',lvl:2},{hz:'花',py:'huā',en:'flower',lvl:2},
  {hz:'树',py:'shù',en:'tree',lvl:2},{hz:'叶',py:'yè',en:'leaf',lvl:2},
  {hz:'果',py:'guǒ',en:'fruit',lvl:2},{hz:'海',py:'hǎi',en:'sea/ocean',lvl:2},
  {hz:'河',py:'hé',en:'river',lvl:2},{hz:'湖',py:'hú',en:'lake',lvl:2},
  // Direction & position
  {hz:'上',py:'shàng',en:'up/above',lvl:2},{hz:'下',py:'xià',en:'down/below',lvl:2},
  {hz:'中',py:'zhōng',en:'middle',lvl:2},{hz:'左',py:'zuǒ',en:'left',lvl:2},
  {hz:'右',py:'yòu',en:'right',lvl:2},{hz:'前',py:'qián',en:'front/before',lvl:2},
  {hz:'后',py:'hòu',en:'back/after',lvl:2},{hz:'里',py:'lǐ',en:'inside',lvl:2},
  {hz:'外',py:'wài',en:'outside',lvl:2},{hz:'旁',py:'páng',en:'beside',lvl:2},
  // Verbs
  {hz:'来',py:'lái',en:'to come',lvl:2},{hz:'去',py:'qù',en:'to go',lvl:2},
  {hz:'吃',py:'chī',en:'to eat',lvl:2},{hz:'喝',py:'hē',en:'to drink',lvl:2},
  {hz:'看',py:'kàn',en:'to look/see',lvl:2},{hz:'说',py:'shuō',en:'to speak',lvl:2},
  {hz:'跑',py:'pǎo',en:'to run',lvl:2},{hz:'玩',py:'wán',en:'to play',lvl:2},
  {hz:'睡',py:'shuì',en:'to sleep',lvl:2},{hz:'起',py:'qǐ',en:'to rise/get up',lvl:2},
  {hz:'走',py:'zǒu',en:'to walk/go',lvl:2},{hz:'站',py:'zhàn',en:'to stand',lvl:2},
  {hz:'坐',py:'zuò',en:'to sit',lvl:3},{hz:'买',py:'mǎi',en:'to buy',lvl:3},
  {hz:'卖',py:'mài',en:'to sell',lvl:3},{hz:'给',py:'gěi',en:'to give',lvl:3},
  {hz:'拿',py:'ná',en:'to take/hold',lvl:3},{hz:'放',py:'fàng',en:'to put/release',lvl:3},
  {hz:'开',py:'kāi',en:'to open/start',lvl:3},{hz:'关',py:'guān',en:'to close',lvl:3},
  {hz:'写',py:'xiě',en:'to write',lvl:3},{hz:'画',py:'huà',en:'to draw',lvl:3},
  {hz:'唱',py:'chàng',en:'to sing',lvl:3},{hz:'跳',py:'tiào',en:'to jump/dance',lvl:3},
  {hz:'打',py:'dǎ',en:'to hit/play',lvl:3},{hz:'问',py:'wèn',en:'to ask',lvl:3},
  {hz:'听',py:'tīng',en:'to listen',lvl:3},{hz:'想',py:'xiǎng',en:'to think/want',lvl:3},
  {hz:'知',py:'zhī',en:'to know',lvl:3},{hz:'道',py:'dào',en:'road/way',lvl:3},
  {hz:'用',py:'yòng',en:'to use',lvl:3},{hz:'做',py:'zuò',en:'to do/make',lvl:3},
  {hz:'有',py:'yǒu',en:'to have',lvl:3},{hz:'没',py:'méi',en:'not have',lvl:3},
  {hz:'是',py:'shì',en:'to be',lvl:3},{hz:'不',py:'bù',en:'not/no',lvl:3},
  // Adjectives
  {hz:'爱',py:'ài',en:'love',lvl:3},{hz:'好',py:'hǎo',en:'good',lvl:3},
  {hz:'多',py:'duō',en:'many/much',lvl:3},{hz:'少',py:'shǎo',en:'few/little',lvl:3},
  {hz:'新',py:'xīn',en:'new',lvl:3},{hz:'旧',py:'jiù',en:'old/worn',lvl:3},
  {hz:'高',py:'gāo',en:'tall/high',lvl:3},{hz:'低',py:'dī',en:'low/short',lvl:3},
  {hz:'长',py:'cháng',en:'long',lvl:3},{hz:'短',py:'duǎn',en:'short',lvl:3},
  {hz:'快',py:'kuài',en:'fast',lvl:3},{hz:'慢',py:'màn',en:'slow',lvl:3},
  {hz:'冷',py:'lěng',en:'cold',lvl:3},{hz:'热',py:'rè',en:'hot',lvl:3},
  {hz:'干',py:'gān',en:'dry',lvl:3},{hz:'湿',py:'shī',en:'wet',lvl:3},
  {hz:'甜',py:'tián',en:'sweet',lvl:3},{hz:'苦',py:'kǔ',en:'bitter',lvl:3},
  {hz:'酸',py:'suān',en:'sour',lvl:3},{hz:'辣',py:'là',en:'spicy',lvl:3},
  // Colours
  {hz:'红',py:'hóng',en:'red',lvl:3},{hz:'黄',py:'huáng',en:'yellow',lvl:3},
  {hz:'绿',py:'lǜ',en:'green',lvl:3},{hz:'白',py:'bái',en:'white',lvl:3},
  {hz:'黑',py:'hēi',en:'black',lvl:3},{hz:'蓝',py:'lán',en:'blue',lvl:3},
  {hz:'紫',py:'zǐ',en:'purple',lvl:3},{hz:'橙',py:'chéng',en:'orange',lvl:3},
  {hz:'粉',py:'fěn',en:'pink',lvl:3},{hz:'灰',py:'huī',en:'grey',lvl:3},
  // Body
  {hz:'手',py:'shǒu',en:'hand',lvl:3},{hz:'眼',py:'yǎn',en:'eye',lvl:3},
  {hz:'口',py:'kǒu',en:'mouth',lvl:3},{hz:'耳',py:'ěr',en:'ear',lvl:3},
  {hz:'头',py:'tóu',en:'head',lvl:3},{hz:'脸',py:'liǎn',en:'face',lvl:3},
  {hz:'鼻',py:'bí',en:'nose',lvl:4},{hz:'牙',py:'yá',en:'tooth',lvl:4},
  {hz:'脚',py:'jiǎo',en:'foot/leg',lvl:4},{hz:'腿',py:'tuǐ',en:'leg',lvl:4},
  {hz:'肚',py:'dù',en:'belly/stomach',lvl:4},{hz:'背',py:'bèi',en:'back',lvl:4},
  // Family
  {hz:'家',py:'jiā',en:'home/family',lvl:4},{hz:'爸',py:'bà',en:'dad',lvl:4},
  {hz:'妈',py:'mā',en:'mum',lvl:4},{hz:'哥',py:'gē',en:'older brother',lvl:4},
  {hz:'姐',py:'jiě',en:'older sister',lvl:4},{hz:'弟',py:'dì',en:'younger brother',lvl:4},
  {hz:'妹',py:'mèi',en:'younger sister',lvl:4},{hz:'爷',py:'yé',en:'grandpa (dad)',lvl:4},
  {hz:'奶',py:'nǎi',en:'grandma (dad)',lvl:4},{hz:'姥',py:'lǎo',en:'grandma (mum)',lvl:4},
  // Animals
  {hz:'鸟',py:'niǎo',en:'bird',lvl:4},{hz:'鱼',py:'yú',en:'fish',lvl:4},
  {hz:'猫',py:'māo',en:'cat',lvl:4},{hz:'狗',py:'gǒu',en:'dog',lvl:4},
  {hz:'马',py:'mǎ',en:'horse',lvl:4},{hz:'牛',py:'niú',en:'cow/ox',lvl:4},
  {hz:'羊',py:'yáng',en:'sheep/goat',lvl:4},{hz:'猪',py:'zhū',en:'pig',lvl:4},
  {hz:'鸡',py:'jī',en:'chicken',lvl:4},{hz:'鸭',py:'yā',en:'duck',lvl:4},
  {hz:'兔',py:'tù',en:'rabbit',lvl:4},{hz:'蛇',py:'shé',en:'snake',lvl:4},
  {hz:'虫',py:'chóng',en:'insect/worm',lvl:4},{hz:'象',py:'xiàng',en:'elephant',lvl:4},
  {hz:'熊',py:'xióng',en:'bear',lvl:4},{hz:'狮',py:'shī',en:'lion',lvl:4},
  // Food & drink
  {hz:'饭',py:'fàn',en:'cooked rice/meal',lvl:4},{hz:'面',py:'miàn',en:'noodles/flour',lvl:4},
  {hz:'菜',py:'cài',en:'vegetable/dish',lvl:4},{hz:'肉',py:'ròu',en:'meat',lvl:4},
  {hz:'鱼',py:'yú',en:'fish',lvl:4},{hz:'蛋',py:'dàn',en:'egg',lvl:4},
  {hz:'米',py:'mǐ',en:'rice (uncooked)',lvl:4},{hz:'盐',py:'yán',en:'salt',lvl:4},
  {hz:'糖',py:'táng',en:'sugar/candy',lvl:4},{hz:'水果',py:'shuǐguǒ',en:'fruit',lvl:4},
  {hz:'苹果',py:'píngguǒ',en:'apple',lvl:4},{hz:'香蕉',py:'xiāngjiāo',en:'banana',lvl:4},
  // Numbers
  {hz:'一',py:'yī',en:'one',lvl:4},{hz:'二',py:'èr',en:'two',lvl:4},
  {hz:'三',py:'sān',en:'three',lvl:4},{hz:'四',py:'sì',en:'four',lvl:4},
  {hz:'五',py:'wǔ',en:'five',lvl:4},{hz:'六',py:'liù',en:'six',lvl:4},
  {hz:'七',py:'qī',en:'seven',lvl:4},{hz:'八',py:'bā',en:'eight',lvl:4},
  {hz:'九',py:'jiǔ',en:'nine',lvl:4},{hz:'十',py:'shí',en:'ten',lvl:4},
  {hz:'百',py:'bǎi',en:'hundred',lvl:4},{hz:'千',py:'qiān',en:'thousand',lvl:4},
  // Time
  {hz:'年',py:'nián',en:'year',lvl:4},{hz:'月',py:'yuè',en:'month',lvl:4},
  {hz:'日',py:'rì',en:'day',lvl:4},{hz:'今',py:'jīn',en:'today/now',lvl:4},
  {hz:'明',py:'míng',en:'tomorrow/bright',lvl:4},{hz:'昨',py:'zuó',en:'yesterday',lvl:4},
  {hz:'早',py:'zǎo',en:'morning/early',lvl:4},{hz:'晚',py:'wǎn',en:'evening/late',lvl:4},
  {hz:'午',py:'wǔ',en:'noon',lvl:4},{hz:'时',py:'shí',en:"time/o'clock",lvl:4},
  // Place & objects
  {hz:'门',py:'mén',en:'door/gate',lvl:4},{hz:'学',py:'xué',en:'to study/learn',lvl:4},
  {hz:'校',py:'xiào',en:'school',lvl:4},{hz:'书',py:'shū',en:'book',lvl:4},
  {hz:'桌',py:'zhuō',en:'table',lvl:4},{hz:'椅',py:'yǐ',en:'chair',lvl:4},
  {hz:'床',py:'chuáng',en:'bed',lvl:4},{hz:'房',py:'fáng',en:'room/house',lvl:4},
  {hz:'车',py:'chē',en:'vehicle/car',lvl:4},{hz:'路',py:'lù',en:'road/path',lvl:4},
  {hz:'店',py:'diàn',en:'shop/store',lvl:4},{hz:'市',py:'shì',en:'city/market',lvl:4},
  // Weather
  {hz:'太阳',py:'tàiyáng',en:'sun',lvl:4},{hz:'星',py:'xīng',en:'star',lvl:4},
  {hz:'光',py:'guāng',en:'light',lvl:4},{hz:'晴',py:'qíng',en:'sunny/clear',lvl:4},
  {hz:'阴',py:'yīn',en:'cloudy/overcast',lvl:4},{hz:'亮',py:'liàng',en:'bright',lvl:4},
  {hz:'暗',py:'àn',en:'dark',lvl:4},{hz:'热',py:'rè',en:'hot',lvl:4},
  // Three Kingdoms & warfare
  {hz:'战',py:'zhàn',en:'battle/war',lvl:5},{hz:'将',py:'jiàng',en:'general',lvl:5},
  {hz:'军',py:'jūn',en:'army',lvl:5},{hz:'兵',py:'bīng',en:'soldier',lvl:5},
  {hz:'王',py:'wáng',en:'king',lvl:5},{hz:'国',py:'guó',en:'kingdom',lvl:5},
  {hz:'城',py:'chéng',en:'city/wall',lvl:5},{hz:'龙',py:'lóng',en:'dragon',lvl:5},
  {hz:'虎',py:'hǔ',en:'tiger',lvl:5},{hz:'英',py:'yīng',en:'hero/brave',lvl:5},
  {hz:'勇',py:'yǒng',en:'brave',lvl:5},{hz:'智',py:'zhì',en:'wisdom',lvl:5},
  {hz:'力',py:'lì',en:'strength',lvl:5},{hz:'胜',py:'shèng',en:'victory',lvl:5},
  {hz:'败',py:'bài',en:'defeat',lvl:5},{hz:'攻',py:'gōng',en:'attack',lvl:5},
  {hz:'守',py:'shǒu',en:'defend',lvl:5},{hz:'刀',py:'dāo',en:'blade',lvl:5},
  {hz:'剑',py:'jiàn',en:'sword',lvl:5},{hz:'弓',py:'gōng',en:'bow',lvl:5},
  {hz:'箭',py:'jiàn',en:'arrow',lvl:5},{hz:'盾',py:'dùn',en:'shield',lvl:5},
  {hz:'甲',py:'jiǎ',en:'armour',lvl:5},{hz:'旗',py:'qí',en:'flag/banner',lvl:5},
  {hz:'鼓',py:'gǔ',en:'drum',lvl:5},{hz:'营',py:'yíng',en:'camp',lvl:5},
  {hz:'帅',py:'shuài',en:'commander',lvl:5},{hz:'阵',py:'zhèn',en:'formation',lvl:5},
  {hz:'围',py:'wéi',en:'surround/siege',lvl:5},{hz:'援',py:'yuán',en:'reinforcement',lvl:5},
  {hz:'粮',py:'liáng',en:'provisions/grain',lvl:5},{hz:'马',py:'mǎ',en:'horse',lvl:5},
  // Virtues & character
  {hz:'义',py:'yì',en:'righteousness',lvl:5},{hz:'仁',py:'rén',en:'benevolence',lvl:5},
  {hz:'忠',py:'zhōng',en:'loyalty',lvl:5},{hz:'信',py:'xìn',en:'trust',lvl:5},
  {hz:'德',py:'dé',en:'virtue/morality',lvl:5},{hz:'礼',py:'lǐ',en:'courtesy/rite',lvl:5},
  {hz:'廉',py:'lián',en:'integrity',lvl:5},{hz:'耻',py:'chǐ',en:'shame',lvl:5},
  {hz:'勤',py:'qín',en:'diligent',lvl:6},{hz:'俭',py:'jiǎn',en:'frugal',lvl:6},
  // Tactics & governance
  {hz:'策',py:'cè',en:'strategy/plan',lvl:6},{hz:'谋',py:'móu',en:'scheme/plan',lvl:6},
  {hz:'计',py:'jì',en:'plan/trick',lvl:6},{hz:'退',py:'tuì',en:'retreat',lvl:6},
  {hz:'进',py:'jìn',en:'advance',lvl:6},{hz:'联',py:'lián',en:'ally/unite',lvl:6},
  {hz:'盟',py:'méng',en:'alliance/oath',lvl:6},{hz:'令',py:'lìng',en:'command/order',lvl:6},
  {hz:'政',py:'zhèng',en:'government',lvl:6},{hz:'法',py:'fǎ',en:'law/method',lvl:6},
  {hz:'治',py:'zhì',en:'to govern',lvl:6},{hz:'乱',py:'luàn',en:'chaos',lvl:6},
  {hz:'平',py:'píng',en:'peace/flat',lvl:6},{hz:'安',py:'ān',en:'peaceful/safe',lvl:6},
  {hz:'危',py:'wēi',en:'danger',lvl:6},{hz:'难',py:'nán',en:'difficult/disaster',lvl:6},
  // Abstract concepts
  {hz:'心',py:'xīn',en:'heart/mind',lvl:6},{hz:'气',py:'qì',en:'breath/spirit',lvl:6},
  {hz:'命',py:'mìng',en:'life/fate',lvl:6},{hz:'运',py:'yùn',en:'luck/destiny',lvl:6},
  {hz:'道',py:'dào',en:'the Way/Tao',lvl:6},{hz:'天',py:'tiān',en:'heaven',lvl:6},
  {hz:'神',py:'shén',en:'god/spirit',lvl:6},{hz:'鬼',py:'guǐ',en:'ghost/demon',lvl:6},
  {hz:'魂',py:'hún',en:'soul',lvl:6},{hz:'志',py:'zhì',en:'will/ambition',lvl:6},
  {hz:'梦',py:'mèng',en:'dream',lvl:6},{hz:'死',py:'sǐ',en:'to die/death',lvl:6},
  {hz:'生',py:'shēng',en:'life/birth',lvl:6},{hz:'存',py:'cún',en:'to exist/preserve',lvl:6},
  {hz:'亡',py:'wáng',en:'to perish/flee',lvl:6},{hz:'兴',py:'xīng',en:'to rise/prosper',lvl:6},
  {hz:'衰',py:'shuāi',en:'to decline/wane',lvl:6},{hz:'灭',py:'miè',en:'to extinguish',lvl:6},
  // Landscape & geography
  {hz:'关',py:'guān',en:'mountain pass',lvl:6},{hz:'桥',py:'qiáo',en:'bridge',lvl:6},
  {hz:'险',py:'xiǎn',en:'dangerous/steep',lvl:6},{hz:'塞',py:'sài',en:'fortress/pass',lvl:6},
  {hz:'原',py:'yuán',en:'plain/meadow',lvl:6},{hz:'谷',py:'gǔ',en:'valley',lvl:6},
  {hz:'岸',py:'àn',en:'bank/shore',lvl:6},{hz:'渡',py:'dù',en:'to cross (water)',lvl:6},
  {hz:'峰',py:'fēng',en:'peak/summit',lvl:6},{hz:'野',py:'yě',en:'wilderness/field',lvl:6},
  // Time & history
  {hz:'史',py:'shǐ',en:'history',lvl:6},{hz:'代',py:'dài',en:'generation/era',lvl:6},
  {hz:'古',py:'gǔ',en:'ancient',lvl:6},{hz:'今',py:'jīn',en:'present/today',lvl:6},
  {hz:'朝',py:'cháo',en:'dynasty/court',lvl:6},{hz:'帝',py:'dì',en:'emperor',lvl:6},
  {hz:'皇',py:'huáng',en:'emperor/imperial',lvl:6},{hz:'臣',py:'chén',en:'minister/subject',lvl:6},
  {hz:'侯',py:'hóu',en:'marquis/noble',lvl:6},{hz:'丞',py:'chéng',en:'prime minister',lvl:6},
  {hz:'相',py:'xiāng',en:'chancellor/each other',lvl:6},{hz:'太',py:'tài',en:'supreme/too much',lvl:6},
  // Weather & celestial
  {hz:'雷',py:'léi',en:'thunder',lvl:6},{hz:'电',py:'diàn',en:'lightning/electricity',lvl:6},
  {hz:'霜',py:'shuāng',en:'frost',lvl:7},{hz:'露',py:'lù',en:'dew',lvl:7},
  {hz:'烟',py:'yān',en:'smoke/mist',lvl:7},{hz:'尘',py:'chén',en:'dust',lvl:7},
  {hz:'浪',py:'làng',en:'wave',lvl:7},{hz:'潮',py:'cháo',en:'tide',lvl:7},
  // More verbs
  {hz:'令',py:'lìng',en:'to order/command',lvl:7},{hz:'奏',py:'zòu',en:'to play music/report to emperor',lvl:7},
  {hz:'封',py:'fēng',en:'to seal/confer title',lvl:7},{hz:'赐',py:'cì',en:'to bestow/grant',lvl:7},
  {hz:'征',py:'zhēng',en:'to conquer/levy',lvl:7},{hz:'讨',py:'tǎo',en:'to punish/suppress',lvl:7},
  {hz:'伐',py:'fá',en:'to attack/campaign',lvl:7},{hz:'降',py:'xiáng',en:'to surrender',lvl:7},
  {hz:'投',py:'tóu',en:'to throw/surrender to',lvl:7},{hz:'逃',py:'táo',en:'to flee/escape',lvl:7},
  {hz:'追',py:'zhuī',en:'to chase/pursue',lvl:7},{hz:'救',py:'jiù',en:'to rescue',lvl:7},
  {hz:'护',py:'hù',en:'to protect/guard',lvl:7},{hz:'杀',py:'shā',en:'to kill',lvl:7},
  {hz:'斩',py:'zhǎn',en:'to behead/cut',lvl:7},{hz:'破',py:'pò',en:'to break/defeat',lvl:7},
  {hz:'夺',py:'duó',en:'to seize/capture',lvl:7},{hz:'占',py:'zhàn',en:'to occupy',lvl:7},
  {hz:'守',py:'shǒu',en:'to guard/defend',lvl:7},{hz:'诈',py:'zhà',en:'to deceive',lvl:7},
  // Personality traits
  {hz:'奸',py:'jiān',en:'treacherous',lvl:7},{hz:'忘',py:'wàng',en:'to forget',lvl:7},
  {hz:'恨',py:'hèn',en:'to hate',lvl:7},{hz:'怒',py:'nù',en:'anger',lvl:7},
  {hz:'喜',py:'xǐ',en:'joy/to like',lvl:7},{hz:'哀',py:'āi',en:'sorrow',lvl:7},
  {hz:'惧',py:'jù',en:'fear',lvl:7},{hz:'怀',py:'huái',en:'to cherish/harbour',lvl:7},
  {hz:'念',py:'niàn',en:'to think of/recite',lvl:7},{hz:'疑',py:'yí',en:'doubt/suspicion',lvl:7},
  // Compound words
  {hz:'天下',py:'tiānxià',en:'the realm/world',lvl:7},{hz:'英雄',py:'yīngxióng',en:'hero',lvl:7},
  {hz:'将军',py:'jiāngjūn',en:'general (title)',lvl:7},{hz:'战场',py:'zhànchǎng',en:'battlefield',lvl:7},
  {hz:'军师',py:'jūnshī',en:'military advisor',lvl:7},{hz:'大将',py:'dàjiàng',en:'great general',lvl:7},
  {hz:'天意',py:'tiānyì',en:'will of heaven',lvl:7},{hz:'人心',py:'rénxīn',en:'human heart',lvl:7},
  {hz:'忠臣',py:'zhōngchén',en:'loyal minister',lvl:7},{hz:'奸臣',py:'jiānchén',en:'treacherous minister',lvl:7},
  // School & learning
  {hz:'文',py:'wén',en:'writing/culture',lvl:7},{hz:'字',py:'zì',en:'character/word',lvl:7},
  {hz:'读',py:'dú',en:'to read',lvl:7},{hz:'写',py:'xiě',en:'to write',lvl:7},
  {hz:'笔',py:'bǐ',en:'pen/brush',lvl:7},{hz:'纸',py:'zhǐ',en:'paper',lvl:7},
  {hz:'墨',py:'mò',en:'ink',lvl:7},{hz:'诗',py:'shī',en:'poem',lvl:7},
  {hz:'歌',py:'gē',en:'song',lvl:7},{hz:'乐',py:'yuè',en:'music',lvl:7},
  {hz:'礼',py:'lǐ',en:'rite/etiquette',lvl:7},{hz:'教',py:'jiào',en:'to teach',lvl:7},
  {hz:'学',py:'xué',en:'to study',lvl:7},{hz:'问',py:'wèn',en:'to ask/question',lvl:7},
  {hz:'答',py:'dá',en:'to answer',lvl:8},{hz:'错',py:'cuò',en:'wrong/mistake',lvl:8},
  {hz:'对',py:'duì',en:'correct/right',lvl:8},{hz:'难',py:'nán',en:'difficult',lvl:8},
  {hz:'易',py:'yì',en:'easy/change',lvl:8},{hz:'懂',py:'dǒng',en:'to understand',lvl:8},
  {hz:'忍',py:'rěn',en:'to endure',lvl:8},{hz:'慎',py:'shèn',en:'careful/cautious',lvl:8},
  {hz:'刚',py:'gāng',en:'firm/just now',lvl:8},{hz:'柔',py:'róu',en:'soft/gentle',lvl:8},
  {hz:'强',py:'qiáng',en:'strong/powerful',lvl:8},{hz:'弱',py:'ruò',en:'weak',lvl:8},
  {hz:'富',py:'fù',en:'wealthy/rich',lvl:8},{hz:'贫',py:'pín',en:'poor',lvl:8},
  {hz:'荣',py:'róng',en:'glory/flourish',lvl:8},{hz:'辱',py:'rǔ',en:'disgrace',lvl:8},
  {hz:'报',py:'bào',en:'to repay/report',lvl:8},{hz:'仇',py:'chóu',en:'enemy/hatred',lvl:8},
  {hz:'恩',py:'ēn',en:'kindness/grace',lvl:8},{hz:'怨',py:'yuàn',en:'resentment',lvl:8},
  {hz:'宽',py:'kuān',en:'broad/tolerant',lvl:8},{hz:'严',py:'yán',en:'strict/severe',lvl:8},
  {hz:'正',py:'zhèng',en:'upright/correct',lvl:8},{hz:'邪',py:'xié',en:'evil/wicked',lvl:8},
  {hz:'善',py:'shàn',en:'good/kind',lvl:8},{hz:'恶',py:'è',en:'evil/wicked',lvl:8},
  {hz:'真',py:'zhēn',en:'true/real',lvl:8},{hz:'假',py:'jiǎ',en:'false/fake',lvl:8},
  {hz:'名',py:'míng',en:'name/fame',lvl:8},{hz:'利',py:'lì',en:'benefit/profit',lvl:8},
  {hz:'势',py:'shì',en:'power/momentum',lvl:8},{hz:'位',py:'wèi',en:'position/seat',lvl:8},
  {hz:'权',py:'quán',en:'power/authority',lvl:8},{hz:'财',py:'cái',en:'wealth/money',lvl:8},
  {hz:'才',py:'cái',en:'talent/ability',lvl:8},{hz:'识',py:'shí',en:'knowledge/recognise',lvl:8},
  // == LEVELS 5-10 · Intermediate & Advanced ==
  // -- Level 6 · Age 9-10 · Odonata Pink complete (~400 chars)
  {hz:'经',py:'jīng',en:'classic/manage',lvl:6},
  {hz:'济',py:'jì',en:'to help/economize',lvl:6},{hz:'社',py:'shè',en:'society',lvl:6},
  {hz:'民',py:'mín',en:'people/civilian',lvl:6},{hz:'族',py:'zú',en:'ethnic group',lvl:6},
  {hz:'语',py:'yǔ',en:'language',lvl:6},{hz:'化',py:'huà',en:'to change/culture',lvl:6},
  {hz:'科',py:'kē',en:'subject/science',lvl:6},{hz:'技',py:'jì',en:'skill/technology',lvl:6},
  {hz:'术',py:'shù',en:'art/technique',lvl:6},{hz:'研',py:'yán',en:'to research',lvl:6},
  {hz:'理',py:'lǐ',en:'reason/manage',lvl:6},{hz:'论',py:'lùn',en:'theory/discuss',lvl:6},
  {hz:'实',py:'shí',en:'real/solid',lvl:6},{hz:'证',py:'zhèng',en:'evidence/prove',lvl:6},
  {hz:'确',py:'què',en:'certain/accurate',lvl:6},{hz:'则',py:'zé',en:'rule/then',lvl:6},
  {hz:'题',py:'tí',en:'topic/question',lvl:6},{hz:'解',py:'jiě',en:'to solve',lvl:6},
  {hz:'决',py:'jué',en:'to decide',lvl:6},{hz:'方',py:'fāng',en:'direction/method',lvl:6},
  {hz:'案',py:'àn',en:'plan/case',lvl:6},{hz:'针',py:'zhēn',en:'needle/policy',lvl:6},
  {hz:'措',py:'cuò',en:'measure/arrange',lvl:6},{hz:'施',py:'shī',en:'to implement',lvl:6},
  {hz:'执',py:'zhí',en:'to execute/hold',lvl:6},{hz:'效',py:'xiào',en:'effect/imitate',lvl:6},
  {hz:'益',py:'yì',en:'benefit/increase',lvl:6},{hz:'行',py:'xíng',en:'to walk/conduct',lvl:6},
  // -- Level 7 · Age 10-12 · HSK 3-4 (~500 chars)
  {hz:'制',py:'zhì',en:'system/manufacture',lvl:7},{hz:'度',py:'dù',en:'degree/system',lvl:7},
  {hz:'统',py:'tǒng',en:'to unite/system',lvl:7},{hz:'整',py:'zhěng',en:'whole/orderly',lvl:7},
  {hz:'体',py:'tǐ',en:'body/style',lvl:7},{hz:'系',py:'xì',en:'system/connect',lvl:7},
  {hz:'结',py:'jié',en:'to tie/result',lvl:7},{hz:'构',py:'gòu',en:'structure',lvl:7},
  {hz:'组',py:'zǔ',en:'group/compose',lvl:7},{hz:'织',py:'zhī',en:'to weave/organise',lvl:7},
  {hz:'机',py:'jī',en:'machine/opportunity',lvl:7},{hz:'器',py:'qì',en:'device/vessel',lvl:7},
  {hz:'具',py:'jù',en:'tool/have',lvl:7},{hz:'产',py:'chǎn',en:'produce/property',lvl:7},
  {hz:'业',py:'yè',en:'industry/occupation',lvl:7},{hz:'商',py:'shāng',en:'commerce/discuss',lvl:7},
  {hz:'贸',py:'mào',en:'trade',lvl:7},{hz:'价',py:'jià',en:'price/value',lvl:7},
  {hz:'值',py:'zhí',en:'value/worth',lvl:7},{hz:'费',py:'fèi',en:'fee/to spend',lvl:7},
  // -- Level 8 · Age 12-14 · HSK 4-5 (~600 chars)
  {hz:'哲',py:'zhé',en:'philosophy/wise',lvl:8},{hz:'观',py:'guān',en:'view/observe',lvl:8},
  {hz:'境',py:'jìng',en:'boundary/situation',lvl:8},{hz:'局',py:'jú',en:'situation/bureau',lvl:8},
  {hz:'临',py:'lín',en:'to face/arrive at',lvl:8},{hz:'遇',py:'yù',en:'to encounter',lvl:8},
  {hz:'困',py:'kùn',en:'difficulty/trapped',lvl:8},{hz:'患',py:'huàn',en:'disaster/worry',lvl:8},
  {hz:'灾',py:'zāi',en:'disaster',lvl:8},{hz:'祸',py:'huò',en:'misfortune',lvl:8},
  {hz:'福',py:'fú',en:'fortune/happiness',lvl:8},{hz:'寿',py:'shòu',en:'longevity',lvl:8},
  {hz:'威',py:'wēi',en:'authority/might',lvl:8},{hz:'猛',py:'měng',en:'fierce/brave',lvl:8},
  {hz:'烈',py:'liè',en:'intense/upright',lvl:8},{hz:'壮',py:'zhuàng',en:'strong/majestic',lvl:8},
  {hz:'雄',py:'xióng',en:'heroic',lvl:8},{hz:'豪',py:'háo',en:'hero/grand',lvl:8},
  {hz:'杰',py:'jié',en:'outstanding person',lvl:8},
  // -- Level 9 · Age 14+ · HSK 5-6 (~700 chars)
  {hz:'辩',py:'biàn',en:'to debate',lvl:9},{hz:'析',py:'xī',en:'to analyse',lvl:9},
  {hz:'归',py:'guī',en:'to return/belong to',lvl:9},{hz:'纳',py:'nà',en:'to accept/include',lvl:9},
  {hz:'述',py:'shù',en:'to narrate',lvl:9},{hz:'评',py:'píng',en:'to evaluate',lvl:9},
  {hz:'判',py:'pàn',en:'to judge',lvl:9},{hz:'断',py:'duàn',en:'to decide',lvl:9},
  {hz:'推',py:'tuī',en:'to push/infer',lvl:9},{hz:'导',py:'dǎo',en:'to lead/guide',lvl:9},
  {hz:'引',py:'yǐn',en:'to lead/quote',lvl:9},{hz:'据',py:'jù',en:'according to',lvl:9},
  {hz:'典',py:'diǎn',en:'classic/standard',lvl:9},{hz:'著',py:'zhù',en:'famous/to write',lvl:9},
  {hz:'章',py:'zhāng',en:'chapter/rule',lvl:9},{hz:'节',py:'jié',en:'section/festival',lvl:9},
  {hz:'句',py:'jù',en:'sentence',lvl:9},{hz:'词',py:'cí',en:'word/lyrics',lvl:9},
  {hz:'含',py:'hán',en:'to contain',lvl:9},{hz:'隐',py:'yǐn',en:'hidden/recluse',lvl:9},
  // -- Level 10 · Adult · All characters
  {hz:'鉴',py:'jiàn',en:'mirror/lesson',lvl:10},{hz:'铭',py:'míng',en:'inscription',lvl:10},
  {hz:'谏',py:'jiàn',en:'to remonstrate',lvl:10},{hz:'诏',py:'zhào',en:'imperial edict',lvl:10},
  {hz:'赦',py:'shè',en:'to pardon',lvl:10},{hz:'偿',py:'cháng',en:'to repay',lvl:10},
  {hz:'债',py:'zhài',en:'debt',lvl:10},{hz:'誓',py:'shì',en:'oath/vow',lvl:10},
  {hz:'藩',py:'fān',en:'vassal/fence',lvl:10},{hz:'镇',py:'zhèn',en:'garrison town',lvl:10},
  {hz:'烽',py:'fēng',en:'beacon fire',lvl:10},
  // Build vocabulary
  {hz:'建',py:'jiàn',en:'to build/construct',lvl:3,tags:['build']},
  {hz:'修',py:'xiū',en:'to repair/build',lvl:3,tags:['build']},
  {hz:'挖',py:'wā',en:'to dig',lvl:3,tags:['build']},
  {hz:'铺',py:'pū',en:'to lay/spread',lvl:3,tags:['build']},
  {hz:'造',py:'zào',en:'to make/construct',lvl:3,tags:['build']},
  {hz:'搬',py:'bān',en:'to move/carry',lvl:3,tags:['build']},
  {hz:'推',py:'tuī',en:'to push',lvl:3,tags:['build']},
  {hz:'拉',py:'lā',en:'to pull',lvl:3,tags:['build']},
  {hz:'切',py:'qiē',en:'to cut',lvl:3,tags:['build']},
  {hz:'挑',py:'tiāo',en:'to carry on pole',lvl:4,tags:['build']},
  {hz:'举',py:'jǔ',en:'to lift/raise',lvl:4,tags:['build']},
  {hz:'堆',py:'duī',en:'to pile up',lvl:4,tags:['build']},
  {hz:'浇',py:'jiāo',en:'to water/pour',lvl:4,tags:['build']},
  {hz:'量',py:'liáng',en:'to measure',lvl:4,tags:['build']},
  {hz:'跌',py:'diē',en:'to fall/trip',lvl:4,tags:['build']},
  {hz:'丢',py:'diū',en:'to throw/lose',lvl:3,tags:['build']},
  {hz:'带',py:'dài',en:'to carry/bring',lvl:3,tags:['build']},
  {hz:'飞',py:'fēi',en:'to fly',lvl:2,tags:['build']},
  {hz:'爬',py:'pá',en:'to climb/crawl',lvl:3,tags:['build']},
  {hz:'锤',py:'chuí',en:'hammer',lvl:5,tags:['build']},
  {hz:'砖',py:'zhuān',en:'brick',lvl:5,tags:['build']},
  {hz:'铁',py:'tiě',en:'iron/steel',lvl:5,tags:['build']},
  {hz:'绳',py:'shéng',en:'rope',lvl:5,tags:['build']},
  {hz:'桶',py:'tǒng',en:'bucket/barrel',lvl:4,tags:['build']},
  {hz:'井',py:'jǐng',en:'well',lvl:4,tags:['build']},
  {hz:'墙',py:'qiáng',en:'wall',lvl:4,tags:['build']},
  {hz:'田',py:'tián',en:'field/farmland',lvl:3,tags:['build']},
  {hz:'工',py:'gōng',en:'work/worker',lvl:3,tags:['build']},
  {hz:'完',py:'wán',en:'finished/complete',lvl:3,tags:['build']},
  {hz:'成',py:'chéng',en:'to succeed/become',lvl:4,tags:['build']},
  // Feast vocabulary
  {hz:'饺',py:'jiǎo',en:'dumpling',lvl:4,tags:['feast']},
  {hz:'包',py:'bāo',en:'bun/wrap',lvl:3,tags:['feast']},
  {hz:'粥',py:'zhōu',en:'congee/porridge',lvl:4,tags:['feast']},
  {hz:'汤',py:'tāng',en:'soup/broth',lvl:3,tags:['feast']},
  {hz:'虾',py:'xiā',en:'shrimp/prawn',lvl:4,tags:['feast']},
  {hz:'豆',py:'dòu',en:'bean/legume',lvl:3,tags:['feast']},
  {hz:'油',py:'yóu',en:'oil/grease',lvl:3,tags:['feast']},
  {hz:'醋',py:'cù',en:'vinegar',lvl:4,tags:['feast']},
  {hz:'酱',py:'jiàng',en:'sauce/paste',lvl:4,tags:['feast']},
  {hz:'香',py:'xiāng',en:'fragrant/delicious',lvl:3,tags:['feast']},
  {hz:'炒',py:'chǎo',en:'to stir-fry',lvl:4,tags:['feast']},
  {hz:'煮',py:'zhǔ',en:'to boil/cook',lvl:4,tags:['feast']},
  {hz:'蒸',py:'zhēng',en:'to steam',lvl:4,tags:['feast']},
  {hz:'烤',py:'kǎo',en:'to roast/grill',lvl:4,tags:['feast']},
  {hz:'碗',py:'wǎn',en:'bowl',lvl:3,tags:['feast']},
  {hz:'盘',py:'pán',en:'plate/dish',lvl:3,tags:['feast']},
  {hz:'杯',py:'bēi',en:'cup/glass',lvl:3,tags:['feast']},
  {hz:'筷',py:'kuài',en:'chopsticks',lvl:4,tags:['feast']},
  {hz:'锅',py:'guō',en:'pot/wok',lvl:4,tags:['feast']},
  {hz:'饿',py:'è',en:'hungry',lvl:3,tags:['feast']},
  {hz:'饱',py:'bǎo',en:'full/satisfied',lvl:4,tags:['feast']},
  {hz:'茶',py:'chá',en:'tea',lvl:3,tags:['feast']},
  {hz:'酒',py:'jiǔ',en:'alcohol/wine',lvl:4,tags:['feast']},
  {hz:'饺子',py:'jiǎozi',en:'dumplings',lvl:3,tags:['feast']},
  {hz:'春卷',py:'chūnjuǎn',en:'spring roll',lvl:4,tags:['feast']},
  {hz:'包子',py:'bāozi',en:'steamed bun',lvl:3,tags:['feast']},
  {hz:'汤圆',py:'tāngyuán',en:'glutinous rice balls',lvl:4,tags:['feast']},
];